[window]
decorations = "Full"
padding = {x = 2, y = 8}
opacity = 0.7

[font]
size=14
   
[cursor]
style={shape="Block", blinking="Always"}
thickness=0.4
blink_interval=600
blink_timeout=0

[colors]
[colors.primary]
foreground = "#9EACC3"
background = "#0f1d1e"

[selection]
save_to_clipboard = true

[mouse]
bindings = [
{ mouse="Right", action="Paste" },
]
